services:
  - type: web
    name: nexus-x-blog
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start-server
    envVars:
      - key: MONGO_CLIENT_ID
        value: mongodb+srv://neroxv1313:Snowfuzzyugen13-@mydb.vv5dhyk.mongodb.net/usersDB?retryWrites=true&w=majority
      - key: REACT_APP_API_URL
        value: http://localhost:3000